config/routes.rb
Rails.application.routes.draw do
  # get 'sessions/new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :blogs
  # resources :blogs, only: [:show]
  # resources :blogs, only: [:create, :new]
  resources :blogs, only: [:create, :new, :edit, :update, :destroy]
  
  root :to => "blogs#index"
  get 'blogs/new' => 'blogs#new'
  post 'blogs' => 'blogs#create'
  get "books/show"
  # get "/blogs/:id" => "blogs#show"
  # get "/blogs#show" => "edit_blog_path"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  validates :title, presence: true, length: { maximum: 50 }
  validates :body, presence: true, length: { maximum: 150 }
  validates :img, presence: true
  mount_uploader :img, ImgUploader
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  # セキュアにハッシュ化したパスワードを、データベース内のpassword_digestという属性に保存できるようになる。
  # 仮想的な属性「password」と「password_confirmation」が使えるようになる。
  # また、存在性と値が一致するかどうかのバリテーションも追加される。
  # authenticateメソッドが使えるようになる。
  # 引数の文字列がパスワードと一致するとUserオブジェクトを、間違っているとfalseを返すメソッド。
  validates :name, presence: true, length: { maximum: 15}
  validates :email, presence: true, length: { maximum: 50}
  validates :password_digest, presence: true, length: { maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  
  private
   # ログイン済みユーザーかどうか確認
    def logged_in_user
      unless logged_in?
        redirect_to login_url
      end
    end
  
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  
  
  def index
    @lists = List.all.order(created_at: :desc)
  end

  def show
    @list = List.find(params[:id])
  end
  
  def new
    @list = List.new
  end
  
  def edit
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to @list, notice: '作成できました'
    else
      render :new, alert: '作成できませんでした'
    end
  end
  
  def update
    if @list.update(list_params)
      redirect_to @list, notice: '更新できました'
    else
      render :edit, alert: '更新できませんでした'
    end
  end
  
  def destroy
    if @list.destroy
      redirect_to root_path, notice: '削除に成功しました'
    else
      redirect_to root_path, alert: '削除に失敗しました'
    end
  end

  private
  
  def list_params
    params.require(:list).permit(:title, :body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to root_url
    else
      render 'new'
    end
  end
  
  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # 渡されたユーザーでログインする
  def log_in(user)
    session[:user_id] = user.id
  end
  
  # 現在ログイン中のユーザーを返す (いる場合)
  def current_user
    if session[:user_id]
     #@current_user = @current_user || User.find_by(id: session[:user_id])と同じ意味
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end
  
  #受け取ったユーザーがログイン中のユーザーと一致すればtrueを返す
  def current_user?(user)
    user == current_user
  end
  
  # ユーザーがログインしていればtrue、その他ならfalseを返す
  def logged_in?
    !current_user.nil?
  end
  
  # 現在のユーザーをログアウトする
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
end

app/views/blogs/_logged_in.html.erb
<!--<p>_logged_in.html</p>-->

<div class="container">
  <div class="logged_main">
  <!-- 画像 -->
  <!--<div class="row">-->
    <div class="col-md-6 wrapper">
      <div class="logo"> 
        <!--<img src="/images/family-album_icon.png" alt="" class="wrapper_logo">-->
      </div>
    </div>

  <!-- 概要 -->
  <div class="blog_tex">
    <h2 class="blog_text">〜子どもの成長をいつまでも〜</h2>
    <p>スマホで撮った子どもの写真や動画をかんたん共有。</p>
    <p>サイト見ながら、家族で楽しく成長をふりかえることができます。</p>
  </div>
    
  <!-- カード -->
  <div class="row card-main">
    <% @lists.each do |blog| %>
        <div class="howe_card-deck col-md-4">
          <div class="home_card">
            <div class="home_image">
              <%= image_tag blog.img.url, class:"home_list_img" %>
            </div>
              <div class="home_card-body col-md-6">
                <p class="home_card-title"><%= link_to blog.title, blog_path(blog), class:"blog_texts" %></p>
                <p class="home_card-text"><%= blog.created_at.strftime("%Y年%m月%d日") %></p>
              </div>
            </div>
        </div>
      <% end %>
  </div>
  </div>
</div>

app/views/blogs/_not_logged_in.html.erb
<!--<p>_not_logged_in.html</p>-->

<div class="container">
  <div class="not_login_comment">
    <div class="not_login_menu">
      <div class="not_login_logo">
        <img src="/images/mini_icon.png" class="mini_logo" alt="mini_logo">
      </div>
      <div class="not_login_logo_two">
        <img src="/images/family-album_logo.png" class="family_logo" alt="family_logo">
      </div>
      <div class="not_login_button">
        <%= image_tag "mini_login_icon.png", class: "login_image_article" %>
        <%= link_to "LOGIN", login_path, class:"loginlogin" %>
      </div>
    </div>
  </div>
</div>

app/views/blogs/edit.html.erb
<!--<p>edit</p>-->

<div class="container">
  <div class="row">
    <div class="col-md-11 edit_post_main">
      <div class="col-md-11 edit_post_icon">
        <h2 class="edit_post_subtitle"><img src="/images/white_post_icon.png" alt="">EDIT POST</h2>
      </div>
      <div class="row">
        <div class="col-md-5 edit_post_image">
          <%= form_for(@list, url: "/blogs") do |f| %>
            <div class="edit_post_img">
              <img src="/images/gg.jpeg" alt="" width="100%" height="auto">
            </div>
            <div class="edit_image_form">
              <%= f.file_field :img, class: "image" %>
            </div>
        </div>
        <div class="col-md-7 edit_post_form">
          <div class="edit_title">
            <h5 class="edit_form-title">Title</h5>
            <%= f.text_field :title, class:"text_title" %>
          </div>
          <div class="edit_post_boby">
            <h5 class="edit_body">Comment</h5>
            <%= f.text_area :body, :placeholder =>"#{@list.body}", class:"edit_text_body" %>
          </div>
         </div>
      </div>
      <div class="edit_buttom">
        <%= f.submit "POST" %>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/blogs/index.erb
<% if logged_in? %>
  <%= render 'blogs/logged_in' %>
<% else %>
  <%= render 'blogs/not_logged_in' %>
<% end %>

app/views/blogs/index.html.erb
<div class="container">
    <h2 class="text-center index_image_top"></h2>
      <% @lists.each do |blog| %>
        <div class="index_article">
          <%= image_tag 'child.jpeg', class: 'index_image_article' %>
            <p><%= link_to blog.title, blog_path(blog) %></p>
              <span>
                <%= blog.created_at.strftime("%Y年%m月%d日") %>
              </span>
              
        </div>
    <% end %>
    
</div>

app/views/blogs/new.html.erb
<!--<p>new.html</p>-->

<div class="container">
  <div class="row">
    <div class="col-md-11 new_post_main">
      <div class="col-md-11 new_post_icon">
        <h2 class="new_post_subtitle"><img src="/images/white_post_icon.png" alt="" class="new_post_icon">NEW POST</h2>
      </div>
      <div class="row">
        <div class="col-md-5 new_post_image">
          <%= form_for(@list, url: "/blogs") do |f| %>
            <div class="new_post_img">
              <img src="/images/gg.jpeg" alt="" width="100%" height="auto">
            </div>
            <div class="image_form">
              <%= f.file_field :img, class: "image" %>
            </div>
        </div>
        <div class="col-md-7 new_post_form">
          <div class="new_title">
            <h5 class="form-title">Title</h5>
            <%= f.text_field :title, class:"text_title" %>
          </div>
          <div class="new_post_boby">
            <h5 class="new_body">Comment</h5>
            <%= f.text_area :body, :placeholder =>"#{@list.body}", class:"text_body" %>
          </div>
         </div>
      </div>
      <div class="new_buttom">
        <%= f.submit "NEW POST" %>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/blogs/show.html.erb
<!--<p>show.html</p>-->

<div class="container" >
  <div class="show_body">
    <div class="show_main">
      <div class="show_title">
          <h2 class="show_card-title"><%= @list.title %></h2>
        </div>
      <div class="show_line">
        <div class="show_image">
          <%= image_tag @list.img.url, class:"show_img"%>
        </div>
        <div class="show_form">
          <div class="show_text">
            <p class="show_card-text"><%= @list.body %></p>
          </div>
        </div>
      </div>
    </div>
    <div class="show_root">
      <a class="nav-link active show_link"><%= link_to image_tag("white_edit_icon.png", class:"edit_switch"), edit_blog_path(@list) %><span class="sr-only">EDIT</span></a>
      <a class="nav-link active show_link"><%= link_to image_tag("white_delete_icon.png", class:"edit_switch"), blog_path, method: :delete %><span class="sr-only">DELETE</span></a>
      <!--<%= link_to 'edit', edit_blog_path(@list) %>-->
      <!--<%= link_to 'delete', blog_path, method: :delete %>-->
    </div>
  </div>
</div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_lists.each do |list| %>
        <li><%= list %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
     
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css">

    <!--<meta name="viewport" content="width=device-width,initial-scale=1">-->
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!--<link rel="stylesheet" href="https://use.typekit.net/twu8mns.css">-->
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
    <!--<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>-->
  
    <title>FAMILY-ALUBUM | 画像投稿サイト</title>
  </head>
  
  <header>
    <div class="container">
     <!-- ナビゲーションメニュー -->
      <nav class="navbar navbar-expand-lg navbar-light bg-dark">
        <a class="navbar-brand text-dark" href="#"><img src="/images/white_oneflower_logo.png" alt="" width="70%" height="60%" class="d-inline-block align-text-top"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ">
          <a class="nav-link text-dark" href="#"> <%= link_to image_tag("white_home_icon.png", class:"home_switch"), root_path %> <span class="sr-only">HOME</span></a>
          <a class="nav-link text-dark" href="#"> <%= link_to image_tag("white_post_icon.png", class:"post_switch"), new_blog_path %> <span class="sr-only">NEWPOST</span></a>
          <a class="nav-link text-dark" href="#"> <%= link_to image_tag("white_logout_icon.png", class:"logout_switch"), logout_path, method: :delete %> <span class="sr-only">LOGOUT</span></a>
        </div>
      </div>
    </nav>
  </div>

  </header>

  <body>
    <%= yield %>
  </body>    
      
  <footer>
    <div class="container"> 
        <div class="footer_main d-flex justify-content-around">
          <ul class="nav justify-content-center bg-dark col-md-12">
            <li class="nav-item">
              <a class="nav-link active"><%= link_to image_tag("white_home_icon.png", class:"home_switch"), root_path %> <span class="sr-only">HOME</span></a>
            </li>
          </ul>
        </div>
      </div>
  </footer>
      
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
  
</html>